name: Demo App
description: >
          A Demo App which does almost nothing of any practical value.
version: 0.0.1-rancher1
category: Demo Apps
maintainer: Nathan Valentine <nathan@rancher.com|nrvale0@gmail.com>
license: not-licensed
projectURL: https://github.com/srikrishna070/catlog-demo.git
